name: Java Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar o Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permissão ao Gradle Wrapper
        run: chmod +x gradlew

      - name: Construir o projeto com Gradle
        run: ./gradlew build

      - name: Executar os testes
        run: ./gradlew test
